name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build, run, and push the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/mateuszjakobschebdy/gh-23417239571234781623:latest
          docker run ghcr.io/mateuszjakobschebdy/gh-23417239571234781623:latest
          docker push ghcr.io/mateuszjakobschebdy/gh-23417239571234781623:latest
